package vista;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import modelo.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Leonardo Méndez
 */
public class VerificacionGUI extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	private List<ProductoEnAlbaran> listaProductosEnAlbaran;
	private List<Producto> listaProductos;

	/**
	 * Creates new form VerificacionGUI
	 */
	public VerificacionGUI(List<ProductoEnAlbaran> listaProductosEnAlbaran, List<Producto> listaProductos) {
		this.listaProductosEnAlbaran = listaProductosEnAlbaran;
		this.listaProductos = listaProductos;
		initComponents(listaProductosEnAlbaran, listaProductos);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents(List<ProductoEnAlbaran> listaProductosEnAlbaran, List<Producto> listaProductos) {

		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		ean_leido_textField = new javax.swing.JTextField();
		btnResultado = new JButton("Resultado");
		

		jLabel2.setText("Listados de articulos verificados:");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null } },
				new String[] { "Código", "Nombre", "Bultos", "Unidades", "Opciones" }) {
			private static final long serialVersionUID = 1L;
			boolean[] canEdit = new boolean[] { false, false, false, true, true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setText("Escanear producto/bulto:");
		ean_leido_textField.addActionListener((java.awt.event.ActionEvent evt) -> {
			jTextField1ActionPerformed(evt);
		});
		ean_leido_textField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField1KeyPressed(evt);
			}
		});
		
		btnResultado.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		// Grupo horizontal
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 174,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(ean_leido_textField,
												GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE) 
								.addComponent(btnResultado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)))
				.addContainerGap()));

		// Grupo vertical
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel1).addComponent(
								ean_leido_textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(btnResultado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		this.setLayout(layout);
		cargarTablaInicial();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {

		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
			String eanLeido = ean_leido_textField.getText().trim();
			if (eanLeido.isEmpty())
				return;

			// 1) Buscar el producto por EAN en la lista completa de productos
			Producto productoLeido = buscarProductoPorEan(eanLeido);
			if (productoLeido == null) {
				javax.swing.JOptionPane.showMessageDialog(this, "EAN no existe en catálogo de productos.", "No encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
				ean_leido_textField.setText("");
				return;
			}

			// 2) Buscar ese producto dentro del albarán (por código)
			ProductoEnAlbaran pea = buscarEnAlbaranPorCodigo(productoLeido.getCodigo());
			if (pea == null) {
				javax.swing.JOptionPane.showMessageDialog(this, "El producto no está en este albarán.",	"No encontrado en albarán", javax.swing.JOptionPane.WARNING_MESSAGE);
				ean_leido_textField.setText("");
				return;
			}

			// 3) Incrementar cantidades recibidas en función del EAN leído
			if (eanLeido.equals(productoLeido.getEanProducto())) {
				pea.setUnidades_recibidas(pea.getUnidades_recibidas() + 1);
			} else if (eanLeido.equals(productoLeido.getEanBulto())) {
				pea.setBultos_recibidos(pea.getBultos_recibidos() + 1);
			}

			// 4) Refrescar tabla
			DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
			model.setRowCount(0);
			for (ProductoEnAlbaran p : listaProductosEnAlbaran) {
				Producto prod = p.getProducto();
				model.addRow(new Object[] { prod.getCodigo(), prod.getNombre(), p.getBultos_recibidos(), p.getUnidades_recibidas(), "Editar" });
			}

			ean_leido_textField.setText("");
			jTable1.revalidate();
			jTable1.repaint();
			ean_leido_textField.requestFocusInWindow();
		}
	}

	private Producto buscarProductoPorEan(String ean) {
		for (Producto p : listaProductos) {
			if (ean.equals(p.getEanProducto()) || ean.equals(p.getEanBulto())) {
				return p;
			}
		}
		return null;
	}

	private ProductoEnAlbaran buscarEnAlbaranPorCodigo(String codigo) {
		System.out.println("Lista a buscar en albarán tiene " + listaProductosEnAlbaran.size() + " productos." + listaProductosEnAlbaran.toString());
		for (ProductoEnAlbaran pea : listaProductosEnAlbaran) {
			if (pea.getProducto() != null && codigo.equals(pea.getProducto().getCodigo())) {
				System.out.println("Producto encontrado en albarán: " + pea.getProducto().getNombre());
				System.out.println("Producto buscado: " + codigo);
				return pea;
			}
		}
		return null;
	}

	private void cargarTablaInicial() {
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0); // limpia
		for (ProductoEnAlbaran pea : listaProductosEnAlbaran) {
			Producto producto = pea.getProducto();
			model.addRow(new Object[] { producto.getCodigo(), producto.getNombre(), pea.getBultos_recibidos(),pea.getUnidades_recibidas(), "Editar" });
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField ean_leido_textField;
	private JButton btnResultado;
	// End of variables declaration//GEN-END:variables
}
