package vista;

import modelo.*;
import controlador.*;


import java.io.File;
import java.util.List;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Leonardo Méndez
 */
public class NuevoGUI extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form NuevoPrueba
	 */
	public NuevoGUI() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton2 = new javax.swing.JButton();

		jLabel1.setText("Seleccionar Albarán:");

		jTextField1.setEditable(false);
		jTextField1.setText("Ruta del Archivo");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton1.setText("Seleccionar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setText("Datos del Albaŕan Seleccionado:");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel3.setText("Articulos");

		// Crear la tabla con el modelo de datos
		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, "" }, { null, null, null, null, null },
						{ null, null, null, null, null }, { null, null, null, null, null },
						{ null, null, null, null, null } },
				new String[] { "Código", "Nombre", "Unidades", "Bultos", "Opciones" }) {
			private static final long serialVersionUID = 1L;
			boolean[] canEdit = new boolean[] { false, false, false, false, true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		// Establecer el tamaño de las columnas
		jScrollPane3.setViewportView(jTable2);
		if (jTable2.getColumnModel().getColumnCount() > 0) {
			jTable2.getColumnModel().getColumn(0).setPreferredWidth(40);
			jTable2.getColumnModel().getColumn(1).setPreferredWidth(80);
			jTable2.getColumnModel().getColumn(4).setPreferredWidth(40);
		}

		jButton2.setText("Verificar");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(19, 19, 19)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(jLabel3).addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jButton2))
										.addComponent(jScrollPane1)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jTextField1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jButton1))
										.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 861,
												Short.MAX_VALUE))
								.addGap(39, 39, 39)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(12, 12, 12)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton2)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF", "pdf");
		fileChooser.setFileFilter(filter);

		int result = fileChooser.showOpenDialog(NuevoGUI.this); // Mostrar el diálogo en el panel
		if (result == JFileChooser.APPROVE_OPTION) {
			File archivoElegido = fileChooser.getSelectedFile();
			jTextField1.setText(archivoElegido.getAbsolutePath());
			List<ProductoEnAlbaran> paraTabla = Controlador.leerAlbaran(archivoElegido);

			// Colocar la información del albarán seleccionado
			Albaran albaran = paraTabla.get(0).getAlbaran();
			jTextArea1.setText("Albarán número: " + albaran.getNumero());
			jTextArea1.append("\n" + "Fecha: " + albaran.getFecha());

			// Limpiar la tabla antes de insertar nuevos datos
			for (int i = 0; i < jTable2.getRowCount(); i++) {
				for (int j = 0; j < jTable2.getColumnCount(); j++) {
					jTable2.setValueAt("", i, j);
				}
			}

			DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); // Obtener el modelo de la tabla

			// Insertar los datos en las celdas, agregando filas si es necesario
			for (int i = 0; i < paraTabla.size(); i++) {
				ProductoEnAlbaran producto = paraTabla.get(i);

				if (i >= jTable2.getRowCount()) {
					model.addRow(new Object[jTable2.getColumnCount()]); // Agregar una nueva fila vacía
				}

				jTable2.setValueAt(producto.getProducto().getCodigo(), i, 0);
				jTable2.setValueAt(producto.getProducto().getNombre(), i, 1);
				jTable2.setValueAt(producto.getCantidadBultos(), i, 2);
				jTable2.setValueAt(producto.getCantidadUnidades(), i, 3);
			}
			
			
			
			// Configurar el JComboBox como editor
            JComboBox<String> comboBox = new JComboBox<>(new String[]{"", "Borrar", "Actualizar"});
            comboBox.setSelectedIndex(-1); // Asegura que no haya selección inicial
            comboBox.addActionListener(e -> {
                int fila = jTable2.getSelectedRow();
                if (fila >= 0) {
                    String opcion = (String) comboBox.getSelectedItem();
                    if (opcion != null && !opcion.isEmpty()) { // Ignorar si es la opción vacía
                        String codigo = (String) model.getValueAt(fila, 0);
                        System.out.println("Fila: " + fila + ", Código: " + codigo + ", Opción: " + opcion);
                        switch (opcion) {
                        	case "Borrar":

                                break;
                            case "Actualizar":

                                break;
                        }
                    }
                }
            });

            TableColumn columnaOpciones = jTable2.getColumnModel().getColumn(4);
            columnaOpciones.setCellEditor(new DefaultCellEditor(comboBox));
            columnaOpciones.setCellRenderer(new ComboBoxRenderer());
		}
		
		

	}// GEN-LAST:event_jButton1ActionPerformed
	
	static class ComboBoxRenderer extends JComboBox<String> implements TableCellRenderer {
        private static final long serialVersionUID = 1L;

        public ComboBoxRenderer() {
            super(new String[]{"", "Borrar", "Actualizar"});
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                               boolean hasFocus, int row, int column) {
            setSelectedItem(value);
            if (isSelected) {
                setBackground(table.getSelectionBackground());
                setForeground(table.getSelectionForeground());
            } else {
                setBackground(table.getBackground());
                setForeground(table.getForeground());
            }
            return this;
        }
    }

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

		// Obtener el contenedor del JPanel actual
		JPanel contenedor = (JPanel) this.getParent();

		// Remover el JPanel actual
		contenedor.remove(this);

		// Agregar el nuevo JPanel
		VerificacionGUI nuevaVerificacion = new VerificacionGUI();

		contenedor.add(nuevaVerificacion);

		// Refrescar la interfaz
		contenedor.revalidate();
		contenedor.repaint();

	}// GEN-LAST:event_jButton2ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
