package vista;

import controlador.Controlador;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Leonardo Méndez
 */
public class ProductosGUI extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form ProductosGUI
	 */
	public ProductosGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();

		jLabel1.setText("Listado de Productos");
		;

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(22).addComponent(jLabel1)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE).addContainerGap()));

		try {
			table = Controlador.tablaProductos();
			if (table != null) {
				jScrollPane1.setViewportView(table);
			} else {
				System.err.println("Error: La tabla no se ha inicializado correctamente.");
			}
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("Error al inicializar la tabla: " + e.getMessage());
		}
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private JTable table;
}
